    <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <!--<title>Zend Framework Quickstart Application</title>-->
          
      <script src="/zend-app/application/views/css/foundation-4.1.1/js/vendor/jquery.js"></script>
      <script src="/zend-app/application/views/css/foundation-4.1.1/js/vendor/custom.modernizr.js"></script>
   
      <?php echo $this->headTitle(); ?>
      <?php echo $this->headLink(); ?>
      
    </head>
<body>
   
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#">Zend</a></h1>
    </li>
   
  </ul>
    <section class="top-bar-section">
        <?php 
    $this->navigation()->menu()->setPartial(array('navigation.phtml','default'));
    
    echo $this->navigation()->menu()->render(); ?>
   
    </section>
</nav>

<div class="row">
    <div class="large-12 columns">
      
  <ul data-orbit data-options="timer_speed:2500; bullets:false;swipe: true">
  <li>
    <img style="height:300px;width:1000px;" src="/zend-app/application/views/css/foundation-4.1.1/img/banners/banner1.jpeg" />
    
  </li>
  <li>
    <img style="height:300px;width:1000px;" src="/zend-app/application/views/css/foundation-4.1.1/img/banners/overflow.jpg" />
    
  </li>
  <li>
    <img style="height:300px;width:1000px;" src="/zend-app/application/views/css/foundation-4.1.1/img/banners/captions.jpg" />
    
  </li>
</ul>
          
</div>
   
</div> <br><br>
    <div class="row">
        <div class="large-4 columns">
            <h4>This is a content section.</h4>
<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
        <div class="large-8 columns">
          <?php echo $this->layout()->content ?>
            </div>
    </div>

<footer class="row">
  <div class="large-12 columns">
   <hr>
   <div class="row">
     <div class="large-6 columns">
       <p>&copy; Copyright no one at all. Go to town.</p>
     </div> 
   </div>
  </div>
</footer>   
<script>
  document.write('<script src=/zend-app/application/views/css/foundation-4.1.1/js/vendor/'
    + ('__proto__' in {} ? 'zepto' : 'jquery')
    + '.js><\/script>');
</script>
 <script src="/zend-app/application/views/css/foundation-4.1.1/js/foundation.min.js"></script>
 <script>
  $(document).foundation();
</script>
    </body>