    <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <!--<title>Zend Framework Quickstart Application</title>-->
          
      <script src="/zend-app/application/views/css/foundation-4.1.1/js/vendor/jquery.js"></script>
      <script src="/zend-app/application/views/css/foundation-4.1.1/js/vendor/custom.modernizr.js"></script>
   
      <?php echo $this->headTitle(); ?>
      <?php echo $this->headLink(); ?>
      
    </head>
<body>
   
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#">Zend</a></h1>
    </li>
   
  </ul>
    <section class="top-bar-section">
        <?php 
    $this->navigation()->menu()->setPartial(array('navigation.phtml','default'));
    
    echo $this->navigation()->menu()->render(); ?>
   
    </section>
</nav>
 
<!--<div class="row">
    <div class="large-12 columns">
      
      <img src="http://placehold.it/1600x600&text=Header">
          
</div>-->
</div>

    </div>
</div>  
    <div class="row">
        <div class="large-9 columns">
            <?php echo $this->layout()->content ?>
        </div>
    </div>
<script>
  document.write('<script src=/zend-app/application/views/css/foundation-4.1.1/js/vendor/'
    + ('__proto__' in {} ? 'zepto' : 'jquery')
    + '.js><\/script>');
</script>
 <script src="/zend-app/application/views/css/foundation-4.1.1/js/foundation.min.js"></script>
 <script>
  $(document).foundation();
</script>
    </body>